# Generated by Django 5.2.14 on 2026-06-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0003_tenant_payment_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronHealth',
            fields=[
                ('job_name', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(default='unknown', max_length=20)),
                ('last_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Cron Health',
            },
        ),
    ]
