# Generated by Django 5.2.16 on 2026-07-21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IdempotencyRecord",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("caller_identity", models.CharField(max_length=160)),
                ("idempotency_key", models.UUIDField()),
                ("operation_id", models.UUIDField(db_index=True)),
                ("correlation_id", models.UUIDField(db_index=True)),
                ("action", models.CharField(max_length=100)),
                ("target_reference", models.CharField(blank=True, max_length=200)),
                ("request_digest", models.CharField(max_length=64)),
                ("state", models.CharField(choices=[("processing", "Processing"), ("completed", "Completed"), ("failed", "Failed")], db_index=True, default="processing", max_length=20)),
                ("response_status", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("response_body", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductControlAuditEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("operation_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("correlation_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("caller_identity", models.CharField(blank=True, max_length=160)),
                ("requested_by", models.CharField(blank=True, max_length=200)),
                ("requester_role", models.CharField(blank=True, max_length=100)),
                ("action", models.CharField(db_index=True, max_length=100)),
                ("target_reference", models.CharField(blank=True, db_index=True, max_length=200)),
                ("request_digest", models.CharField(blank=True, max_length=64)),
                ("outcome", models.CharField(choices=[("accepted", "Accepted"), ("completed", "Completed"), ("rejected", "Rejected"), ("failed", "Failed"), ("duplicate", "Duplicate")], max_length=20)),
                ("error_code", models.CharField(blank=True, max_length=80)),
                ("before_state", models.JSONField(blank=True, default=dict)),
                ("after_state", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="RequestNonce",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key_id", models.CharField(max_length=100)),
                ("nonce", models.CharField(max_length=128)),
                ("caller_identity", models.CharField(max_length=160)),
                ("request_digest", models.CharField(max_length=64)),
                ("request_timestamp", models.DateTimeField()),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.AddConstraint(model_name="idempotencyrecord", constraint=models.UniqueConstraint(fields=("caller_identity", "idempotency_key"), name="control_api_unique_caller_idempotency")),
        migrations.AddConstraint(model_name="idempotencyrecord", constraint=models.UniqueConstraint(fields=("caller_identity", "operation_id"), name="control_api_unique_caller_operation")),
        migrations.AddIndex(model_name="requestnonce", index=models.Index(fields=["caller_identity", "created_at"], name="control_api_rate_idx")),
        migrations.AddConstraint(model_name="requestnonce", constraint=models.UniqueConstraint(fields=("key_id", "nonce"), name="control_api_unique_key_nonce")),
    ]
