# Generated by Django 5.2.11 on 2026-05-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('room_type', models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Twin', 'Twin'), ('Family', 'Family'), ('Suite', 'Suite'), ('Self-Catering', 'Self-Catering')], max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_guests', models.IntegerField(default=2)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Cleaning', 'Cleaning'), ('Maintenance', 'Maintenance'), ('Blocked', 'Blocked')], default='Available', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='rooms/')),
                ('internal_notes', models.TextField(blank=True)),
                ('cleaning_status', models.CharField(choices=[('Clean', 'Clean'), ('Needs Cleaning', 'Needs Cleaning'), ('In Progress', 'In Progress')], default='Clean', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
