# Generated by Django 5.2.11 on 2026-05-11 14:02

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_guest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('num_guests', models.IntegerField(default=1)),
                ('rate_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('deposit_required', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('deposit_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('balance_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('booking_source', models.CharField(choices=[('Walk-in', 'Walk-in'), ('Phone Call', 'Phone Call'), ('WhatsApp', 'WhatsApp'), ('Booking.com', 'Booking.com'), ('Airbnb', 'Airbnb'), ('Website', 'Website'), ('Referral', 'Referral'), ('Other', 'Other')], default='Walk-in', max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Checked In', 'Checked In'), ('Checked Out', 'Checked Out'), ('Cancelled', 'Cancelled'), ('No Show', 'No Show')], default='Pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking_reference', models.CharField(blank=True, max_length=20, unique=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='core.guest')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='core.room')),
            ],
            options={
                'ordering': ['-check_in_date', '-created_at'],
            },
        ),
    ]
