# Generated by Django 5.2.11 on 2026-05-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_booking_check_in_time_booking_check_out_time_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('Cleaning', 'Cleaning'), ('Maintenance', 'Maintenance'), ('Utilities', 'Utilities'), ('Supplies', 'Supplies'), ('Staff', 'Staff'), ('Marketing', 'Marketing'), ('Other', 'Other')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_to', models.CharField(blank=True, max_length=150)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('EFT', 'EFT'), ('Card', 'Card'), ('Other', 'Other')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
