# Generated by Django 5.2.11 on 2026-05-13 12:36

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('guest_house_name', models.CharField(max_length=200)),
                ('owner_email', models.EmailField(max_length=254)),
                ('license_key', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('trial_extended', models.BooleanField(default=False)),
                ('converted_to_paid', models.BooleanField(default=False)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-activated_at'],
            },
        ),
        migrations.AlterField(
            model_name='room',
            name='base_price',
            field=models.DecimalField(db_column='base_price', decimal_places=2, max_digits=10),
        ),
        migrations.RenameField(
            model_name='room',
            old_name='base_price',
            new_name='price_per_night',
        ),
        migrations.RemoveField(
            model_name='room',
            name='image',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_duration_type',
            field=models.CharField(choices=[('1_hour', '1 Hour'), ('2_hours', '2 Hours'), ('3_hours', '3 Hours'), ('5_hours', '5 Hours'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guesthousesettings',
            name='early_checkin_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='guesthousesettings',
            name='enable_hourly_bookings',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='guesthousesettings',
            name='enable_weekly_bookings',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='guesthousesettings',
            name='hourly_booking_label',
            field=models.CharField(default='Short Stay', max_length=100),
        ),
        migrations.AddField(
            model_name='guesthousesettings',
            name='late_checkout_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Extra charge for late checkout', max_digits=10),
        ),
        migrations.AddField(
            model_name='guesthousesettings',
            name='minimum_hourly_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='guesthousesettings',
            name='pos_api_key',
            field=models.CharField(blank=True, help_text='Secret key for POS integration', max_length=100),
        ),
        migrations.AddField(
            model_name='guesthousesettings',
            name='seasonal_note',
            field=models.TextField(blank=True, help_text='Note shown on availability page'),
        ),
        migrations.AddField(
            model_name='guesthousesettings',
            name='weekend_surcharge_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='% extra on Fri/Sat nights', max_digits=5),
        ),
        migrations.AddField(
            model_name='room',
            name='booking_types_allowed',
            field=models.CharField(default='Daily', max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='price_1_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='price_2_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='price_3_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='price_5_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='price_per_week',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='POSTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_reference', models.CharField(max_length=100, unique=True)),
                ('pos_system', models.CharField(default='Unknown POS', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='R', max_length=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('processing_notes', models.TextField(blank=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_transactions', to='core.booking')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
