# Generated by Django 5.2.11 on 2026-05-13 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_triallicense_alter_room_base_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('annual_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_rooms', models.IntegerField(default=8)),
                ('max_users', models.IntegerField(default=1)),
                ('feature_expenses', models.BooleanField(default=False)),
                ('feature_full_reports', models.BooleanField(default=False)),
                ('feature_export', models.BooleanField(default=False)),
                ('feature_hourly_bookings', models.BooleanField(default=False)),
                ('feature_weekly_bookings', models.BooleanField(default=False)),
                ('feature_inventory', models.BooleanField(default=False)),
                ('feature_staff_roles', models.BooleanField(default=False)),
                ('feature_pos_integration', models.BooleanField(default=False)),
                ('feature_multi_property', models.BooleanField(default=False)),
                ('feature_api_access', models.BooleanField(default=False)),
                ('feature_custom_pdf_branding', models.BooleanField(default=False)),
                ('feature_maintenance_requests', models.BooleanField(default=False)),
                ('feature_priority_support', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['monthly_price'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=10)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended')], default='trial', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('owner_name', models.CharField(max_length=200)),
                ('owner_email', models.EmailField(max_length=254)),
                ('owner_phone', models.CharField(blank=True, max_length=20)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('last_payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('last_payment_reference', models.CharField(blank=True, max_length=100)),
                ('next_billing_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.subscriptionplan')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
