# Generated by Django 6.0.5 on 2026-05-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_poscategory_positem_possale_possaleitem_posshift_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={'ordering': ['-is_generic', 'last_name', 'first_name']},
        ),
        migrations.AddField(
            model_name='guest',
            name='is_generic',
            field=models.BooleanField(default=False),
        ),
    ]
