# Generated by Codex on 2026-05-15

from decimal import Decimal

from django.db import migrations, models


def seed_default_rates(apps, schema_editor):
    GuestHouseSettings = apps.get_model("core", "GuestHouseSettings")
    Room = apps.get_model("core", "Room")
    settings_obj = GuestHouseSettings.objects.filter(pk=1).first()
    if not settings_obj:
        return

    first_room = Room.objects.order_by("pk").first()
    settings_obj.default_price_2_hours = getattr(first_room, "price_2_hours", None) or Decimal("0.00")
    settings_obj.default_price_3_hours = getattr(first_room, "price_3_hours", None) or Decimal("0.00")
    settings_obj.default_price_per_night = getattr(first_room, "price_per_night", None) or Decimal("0.00")
    settings_obj.default_price_24_hours = getattr(first_room, "price_per_night", None) or Decimal("0.00")
    settings_obj.save(
        update_fields=[
            "default_price_2_hours",
            "default_price_3_hours",
            "default_price_per_night",
            "default_price_24_hours",
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_create_staff_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="guesthousesettings",
            name="default_price_2_hours",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
        ),
        migrations.AddField(
            model_name="guesthousesettings",
            name="default_price_3_hours",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
        ),
        migrations.AddField(
            model_name="guesthousesettings",
            name="default_price_per_night",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
        ),
        migrations.AddField(
            model_name="guesthousesettings",
            name="default_price_24_hours",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
        ),
        migrations.RunPython(seed_default_rates, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="booking",
            name="booking_duration_type",
            field=models.CharField(
                choices=[
                    ("1_hour", "1 Hour"),
                    ("2_hours", "2 Hours"),
                    ("3_hours", "3 Hours"),
                    ("5_hours", "5 Hours"),
                    ("daily", "Daily"),
                    ("24_hours", "24 Hours"),
                    ("weekly", "Weekly"),
                ],
                default="daily",
                max_length=20,
            ),
        ),
    ]
