# Generated by Django 6.0.5 on 2026-05-19 10:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_cleaningproof'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refund_date', models.DateField(default=django.utils.timezone.localdate)),
                ('refund_method', models.CharField(choices=[('Cash', 'Cash'), ('EFT', 'EFT'), ('Card', 'Card'), ('Other', 'Other')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('reason', models.TextField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_booking_refunds', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='core.booking')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_booking_refunds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-refund_date', '-recorded_at'],
            },
        ),
    ]
