# Generated by Django 5.2.14 on 2026-06-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_subscription_payfast_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('EFT', 'EFT'), ('Card', 'Card'), ('SnapScan', 'SnapScan'), ('Zapper', 'Zapper'), ('Bank Deposit', 'Bank Deposit'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('Payment', 'Payment'), ('Deposit', 'Deposit')], max_length=20),
        ),
    ]
