# Generated by Django 5.2.14 on 2026-06-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_guesthouse_onboarding'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='vehicle_registration',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
