# Generated by Django 5.2.14 on 2026-06-19 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_booking_vehicle_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='positem',
            name='prop',
        ),
        migrations.RemoveField(
            model_name='possaleitem',
            name='pos_item',
        ),
        migrations.RemoveField(
            model_name='possale',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='possale',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='possale',
            name='original_sale',
        ),
        migrations.RemoveField(
            model_name='possale',
            name='prop',
        ),
        migrations.RemoveField(
            model_name='possale',
            name='served_by',
        ),
        migrations.RemoveField(
            model_name='possale',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='possaleitem',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='posshift',
            name='closed_by',
        ),
        migrations.RemoveField(
            model_name='posshift',
            name='opened_by',
        ),
        migrations.RemoveField(
            model_name='posshift',
            name='prop',
        ),
        migrations.RemoveField(
            model_name='postransaction',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='guesthousesettings',
            name='pos_api_key',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='feature_pos_integration',
        ),
        migrations.DeleteModel(
            name='POSCategory',
        ),
        migrations.DeleteModel(
            name='POSItem',
        ),
        migrations.DeleteModel(
            name='POSSale',
        ),
        migrations.DeleteModel(
            name='POSSaleItem',
        ),
        migrations.DeleteModel(
            name='POSShift',
        ),
        migrations.DeleteModel(
            name='POSTransaction',
        ),
    ]
