# Generated by Django 5.2.14 on 2026-06-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_offline_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='guesthousesettings',
            name='pdf_primary_color',
            field=models.CharField(default='#c9a84c', help_text='Brand colour used across all PDF exports (hex, e.g. #c9a84c)', max_length=7),
        ),
    ]
