# Generated by Django 5.2.14 on 2026-06-22 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_add_pdf_primary_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='feature_spa',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SpaService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('massage', 'Massage'), ('facial', 'Facial'), ('body', 'Body Treatment'), ('nail', 'Nail Care'), ('hair', 'Hair'), ('hydrotherapy', 'Hydrotherapy'), ('wellness', 'Wellness & Meditation'), ('other', 'Other')], default='massage', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='Duration in minutes')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spa_services', to='core.property')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SpaAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, help_text='Walk-in guest name (if no guest profile)', max_length=200)),
                ('guest_phone', models.CharField(blank=True, max_length=30)),
                ('therapist', models.CharField(blank=True, help_text='Name of therapist', max_length=200)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='pending', max_length=20)),
                ('price_charged', models.DecimalField(decimal_places=2, help_text='Actual price charged', max_digits=10)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('deposit_paid', 'Deposit Paid'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='unpaid', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(blank=True, help_text='Link to room booking (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spa_appointments', to='core.booking')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spa_appointments_created', to=settings.AUTH_USER_MODEL)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spa_appointments', to='core.guest')),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spa_appointments', to='core.property')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='core.spaservice')),
            ],
            options={
                'ordering': ['scheduled_date', 'scheduled_time'],
            },
        ),
    ]
