# Generated by Django 5.2.14 on 2026-06-22 09:27

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_spa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='spaappointment',
            name='commission_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='spaappointment',
            name='consultation_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='spaappointment',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spaappointment',
            name='tip_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.CreateModel(
            name='SpaPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('package_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spa_packages', to='core.property')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='spaappointment',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='core.spapackage'),
        ),
        migrations.CreateModel(
            name='SpaPackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.spapackage')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_items', to='core.spaservice')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SpaTherapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('specialties', models.TextField(blank=True, help_text='Services this therapist specialises in')),
                ('commission_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Commission percentage (e.g. 15 = 15%)', max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spa_therapists', to='core.property')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SpaClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergies', models.TextField(blank=True)),
                ('contraindications', models.TextField(blank=True, help_text='Medical conditions or medications to be aware of')),
                ('skin_type', models.CharField(blank=True, choices=[('normal', 'Normal'), ('dry', 'Dry'), ('oily', 'Oily'), ('combination', 'Combination'), ('sensitive', 'Sensitive')], max_length=20)),
                ('pressure_preference', models.CharField(blank=True, choices=[('light', 'Light'), ('medium', 'Medium'), ('firm', 'Firm'), ('deep', 'Deep Tissue')], max_length=20)),
                ('general_notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spa_profile', to='core.guest')),
                ('preferred_therapist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_by_clients', to='core.spatherapist')),
            ],
        ),
        migrations.AddField(
            model_name='spaappointment',
            name='assigned_therapist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='core.spatherapist'),
        ),
        migrations.CreateModel(
            name='SpaTreatmentRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spa_treatment_rooms', to='core.property')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='spaappointment',
            name='treatment_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='core.spatreatmentroom'),
        ),
        migrations.CreateModel(
            name='SpaVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=20, unique=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('issued_to_name', models.CharField(max_length=200)),
                ('issued_to_email', models.EmailField(blank=True, max_length=254)),
                ('issued_to_phone', models.CharField(blank=True, max_length=30)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spa_vouchers_issued', to=settings.AUTH_USER_MODEL)),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spa_vouchers', to='core.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='spaappointment',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='core.spavoucher'),
        ),
        migrations.CreateModel(
            name='SpaWaitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('guest_name', models.CharField(blank=True, max_length=200)),
                ('guest_phone', models.CharField(blank=True, max_length=30)),
                ('guest_email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('notified', 'Notified'), ('booked', 'Booked'), ('expired', 'Expired')], default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spa_waitlist', to='core.guest')),
                ('preferred_therapist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_entries', to='core.spatherapist')),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spa_waitlist', to='core.property')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_entries', to='core.spaservice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpaServiceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='Quantity of this product consumed per treatment', max_digits=8)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spa_service_usage', to='core.inventoryitem')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_usage', to='core.spaservice')),
            ],
            options={
                'unique_together': {('service', 'inventory_item')},
            },
        ),
    ]
