# Generated by Django 5.2.14 on 2026-06-22 11:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_spa_premium'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('EFT', 'EFT'), ('Card', 'Card'), ('SnapScan', 'SnapScan'), ('Zapper', 'Zapper'), ('Bank Deposit', 'Bank Deposit'), ('Other', 'Other')], max_length=20)),
                ('payment_type', models.CharField(choices=[('Payment', 'Payment'), ('Deposit', 'Deposit')], default='Payment', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spa_payments', to='core.spaappointment')),
            ],
            options={
                'ordering': ['-payment_date', '-recorded_at'],
            },
        ),
    ]
