# Generated by Django 5.2.14 on 2026-07-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_control_user_login_telemetry'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='pricing_model',
            field=models.CharField(choices=[('per_room', 'Per Room'), ('per_person', 'Per Person')], default='per_room', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Twin', 'Twin'), ('Family', 'Family'), ('Suite', 'Suite'), ('En-Suite', 'En-Suite'), ('Self-Catering', 'Self-Catering'), ('Dormitory', 'Dormitory')], max_length=20),
        ),
    ]
