# Generated by Django 5.2.14 on 2026-07-27 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_room_type_and_pricing_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='ZAR', max_length=3)),
                ('pricing_basis', models.CharField(choices=[('per_person_per_night', 'Per Person Per Night'), ('per_room_per_night', 'Per Room Per Night')], default='per_person_per_night', max_length=25)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('bathroom_type', models.CharField(choices=[('private', 'Private'), ('communal', 'Communal'), ('pending', 'Pending Confirmation')], default='private', max_length=10)),
                ('bathroom_description', models.CharField(blank=True, max_length=255)),
                ('gender_restriction', models.CharField(choices=[('none', 'No Restriction'), ('ladies', 'Ladies Only'), ('gentlemen', 'Gentlemen Only')], default='none', max_length=10)),
                ('is_wheelchair_accessible', models.BooleanField(default=False)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('default_rate_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_types', to='core.rateplan')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Room Types',
            },
        ),
        migrations.AddField(
            model_name='room',
            name='room_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='core.roomtype'),
        ),
        migrations.AddField(
            model_name='room',
            name='rate_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='core.rateplan'),
        ),
    ]
