# Generated by Django 5.2.14 on 2026-07-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_room_type_and_rate_plan_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='guesthousesettings',
            name='shared_capacity_booking_enabled',
            field=models.BooleanField(default=False, help_text='Allow rooms configured as Shared Capacity to take multiple overlapping bookings up to room capacity.'),
        ),
        migrations.AddField(
            model_name='room',
            name='booking_mode',
            field=models.CharField(choices=[('WHOLE_ROOM', 'Whole Room'), ('SHARED_CAPACITY', 'Shared Capacity')], default='WHOLE_ROOM', max_length=20),
        ),
    ]
