# Generated by Django 5.2.14 on 2026-06-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='notes_internal',
            field=models.TextField(blank=True, help_text='Internal Circle Core notes — not visible to customer'),
        ),
    ]
