# Generated by Django 5.2.14 on 2026-06-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_alter_lead_notes_internal'),
    ]

    operations = [
        migrations.AddField(
            model_name='guesthousetenant',
            name='notes_internal',
            field=models.TextField(blank=True),
        ),
    ]
