from django.urls import path

from . import offline_views, views


app_name = "core"

urlpatterns = [
    path("", views.home, name="home"),
    path("onboarding/", views.onboarding, name="onboarding"),
    path("onboarding/clear-demo/", views.onboarding_clear_demo, name="onboarding_clear_demo"),
    path("api/notifications/", views.notifications_feed, name="notifications_feed"),
    path("offline/", offline_views.offline_console, name="offline_console"),
    path("offline/manage/", offline_views.offline_management, name="offline_management"),
    path("offline/conflicts/<int:pk>/resolve/", offline_views.offline_conflict_resolve, name="offline_conflict_resolve"),
    path("api/offline/enroll/", offline_views.offline_enroll, name="offline_enroll"),
    path("api/offline/bootstrap/", offline_views.offline_bootstrap, name="offline_bootstrap"),
    path("api/offline/sync/", offline_views.offline_sync, name="offline_sync"),
    path("search/", views.search, name="search"),
    path("availability/", views.availability, name="availability"),
    path("reports/", views.reports, name="reports"),
    path("daily-close/", views.daily_close, name="daily_close"),
    path("daily-close/lock/", views.daily_close_lock, name="daily_close_lock"),
    path("daily-close/<int:pk>/unlock/", views.daily_close_unlock, name="daily_close_unlock"),
    path("calendar/", views.room_calendar, name="room_calendar"),
    path("communications/", views.communications_center, name="communications"),
    path("housekeeping/mobile/", views.housekeeping_mobile, name="housekeeping_mobile"),
    path("export/<str:dataset>/", views.export_data, name="export_data"),
    path("settings/", views.settings_view, name="settings"),
    path("properties/", views.property_list, name="property_list"),
    path("properties/add/", views.property_add, name="property_add"),
    path("properties/<int:pk>/edit/", views.property_edit, name="property_edit"),
    path("properties/switch/<int:pk>/", views.property_switch, name="property_switch"),
    path("staff/", views.staff_list, name="staff_list"),
    path("staff/add/", views.staff_add, name="staff_add"),
    path("staff/<int:pk>/edit/", views.staff_edit, name="staff_edit"),
    path("staff/<int:pk>/delete/", views.staff_delete, name="staff_delete"),
    path("subscription/plans/", views.plans_page, name="plans_page"),
    path("subscription/upgrade/", views.subscription_upgrade, name="subscription_upgrade"),
    path("subscription/expired/", views.subscription_expired, name="subscription_expired"),
    path("subscription/setup/", views.subscription_setup, name="subscription_setup"),
    path("subscription/status/", views.subscription_status, name="subscription_status"),
    path("trial/setup/", views.trial_setup, name="trial_setup"),
    path("trial/expired/", views.trial_expired, name="trial_expired"),
    path("api/bookings/completed-reminders/", views.completed_booking_reminders_api, name="completed_booking_reminders_api"),
    path("rooms/", views.room_list, name="room_list"),
    path("rooms/add/", views.room_add, name="room_add"),
    path("rooms/<int:pk>/", views.room_detail, name="room_detail"),
    path("rooms/<int:pk>/edit/", views.room_edit, name="room_edit"),
    path("rooms/<int:pk>/delete/", views.room_delete, name="room_delete"),
    path("cleaning/", views.cleaning_board, name="cleaning"),
    path("cleaning/proofs/", views.cleaning_proof_review, name="cleaning_proof_review"),
    path("cleaning/proofs/<int:pk>/photo/", views.cleaning_proof_photo, name="cleaning_proof_photo"),
    path("cleaning/room/<int:pk>/set-status/", views.cleaning_set_status, name="cleaning_set_status"),
    path("maintenance/", views.maintenance_board, name="maintenance_board"),
    path("maintenance/add/", views.maintenance_add, name="maintenance_add"),
    path("maintenance/<int:pk>/", views.maintenance_detail, name="maintenance_detail"),
    path("maintenance/<int:pk>/edit/", views.maintenance_edit, name="maintenance_edit"),
    path("maintenance/<int:pk>/set-status/", views.maintenance_set_status, name="maintenance_set_status"),
    path("inventory/", views.inventory_dashboard, name="inventory_dashboard"),
    path("inventory/add/", views.inventory_add, name="inventory_add"),
    path("inventory/transactions/", views.inventory_transactions, name="inventory_transactions"),
    path("inventory/categories/", views.inventory_categories, name="inventory_categories"),
    path("inventory/<int:pk>/", views.inventory_detail, name="inventory_detail"),
    path("inventory/<int:pk>/edit/", views.inventory_edit, name="inventory_edit"),
    path("inventory/<int:pk>/stock-in/", views.inventory_stock_in, name="inventory_stock_in"),
    path("inventory/<int:pk>/stock-out/", views.inventory_stock_out, name="inventory_stock_out"),
    path("expenses/", views.expense_list, name="expense_list"),
    path("expenses/add/", views.expense_add, name="expense_add"),
    path("expenses/<int:pk>/edit/", views.expense_edit, name="expense_edit"),
    path("expenses/<int:pk>/delete/", views.expense_delete, name="expense_delete"),
    path("guests/", views.guest_list, name="guest_list"),
    path("guests/add/", views.guest_add, name="guest_add"),
    path("guests/quick-create/", views.guest_quick_create, name="guest_quick_create"),
    path("guests/<int:pk>/", views.guest_detail, name="guest_detail"),
    path("guests/<int:pk>/edit/", views.guest_edit, name="guest_edit"),
    path("bookings/", views.booking_list, name="booking_list"),
    path("bookings/add/", views.booking_add, name="booking_add"),
    path("payments/", views.payment_list, name="payment_list"),
    path("security/exceptions/", views.exception_report, name="exception_report"),
    path("security/audit/", views.audit_timeline, name="audit_timeline"),
    path("bookings/<int:pk>/", views.booking_detail, name="booking_detail"),
    path("bookings/<int:booking_id>/payments/add/", views.payment_add, name="payment_add"),
    path("bookings/<int:booking_id>/refund/", views.booking_refund, name="booking_refund"),
    path("bookings/<int:booking_id>/payments/<int:payment_id>/delete/", views.payment_delete, name="payment_delete"),
    path("bookings/<int:pk>/pdf/confirmation/", views.booking_confirmation_pdf, name="booking_confirmation_pdf"),
    path("bookings/<int:pk>/pdf/invoice/", views.booking_invoice_pdf, name="booking_invoice_pdf"),
    path("bookings/<int:pk>/whatsapp/<str:template_name>/", views.booking_whatsapp, name="booking_whatsapp"),
    path(
        "bookings/<int:booking_id>/payments/<int:payment_id>/pdf/receipt/",
        views.payment_receipt_pdf,
        name="payment_receipt_pdf",
    ),
    path("bookings/<int:pk>/edit/", views.booking_edit, name="booking_edit"),
    path("bookings/<int:pk>/check-in/", views.booking_checkin, name="booking_checkin"),
    path("bookings/<int:pk>/check-out/", views.booking_checkout, name="booking_checkout"),
    path("bookings/<int:pk>/no-show/", views.booking_no_show, name="booking_no_show"),
    path("bookings/<int:pk>/cancel/", views.booking_cancel, name="booking_cancel"),
    # Command Center impersonation entry
    path("command-enter/", views.command_enter, name="command_enter"),
    # Spa & Wellness — dashboard
    path("spa/", views.spa_dashboard, name="spa_dashboard"),
    path("spa/schedule/", views.spa_schedule, name="spa_schedule"),
    path("spa/reports/", views.spa_reports, name="spa_reports"),
    # Appointments
    path("spa/appointments/", views.spa_appointment_list, name="spa_appointment_list"),
    path("spa/appointments/add/", views.spa_appointment_add, name="spa_appointment_add"),
    path("spa/appointments/<int:pk>/", views.spa_appointment_detail, name="spa_appointment_detail"),
    path("spa/appointments/<int:pk>/edit/", views.spa_appointment_edit, name="spa_appointment_edit"),
    path("spa/appointments/<int:pk>/receipt/", views.spa_appointment_receipt, name="spa_appointment_receipt"),
    path("spa/appointments/<int:pk>/payment/add/", views.spa_payment_add, name="spa_payment_add"),
    path("spa/appointments/<int:pk>/payment/<int:payment_id>/delete/", views.spa_payment_delete, name="spa_payment_delete"),
    # Services
    path("spa/services/", views.spa_services, name="spa_services"),
    path("spa/services/<int:pk>/edit/", views.spa_service_edit, name="spa_service_edit"),
    path("spa/services/<int:pk>/delete/", views.spa_service_delete, name="spa_service_delete"),
    # Therapists
    path("spa/therapists/", views.spa_therapists, name="spa_therapists"),
    path("spa/therapists/<int:pk>/edit/", views.spa_therapist_edit, name="spa_therapist_edit"),
    path("spa/therapists/<int:pk>/delete/", views.spa_therapist_delete, name="spa_therapist_delete"),
    path("spa/therapists/<int:therapist_pk>/day-sheet/", views.spa_therapist_day_sheet, name="spa_therapist_day_sheet"),
    # Treatment Rooms
    path("spa/rooms/", views.spa_treatment_rooms, name="spa_treatment_rooms"),
    path("spa/rooms/<int:pk>/edit/", views.spa_treatment_room_edit, name="spa_treatment_room_edit"),
    path("spa/rooms/<int:pk>/delete/", views.spa_treatment_room_delete, name="spa_treatment_room_delete"),
    # Packages
    path("spa/packages/", views.spa_packages, name="spa_packages"),
    path("spa/packages/<int:pk>/", views.spa_package_detail, name="spa_package_detail"),
    path("spa/packages/<int:pk>/delete/", views.spa_package_delete, name="spa_package_delete"),
    # Vouchers
    path("spa/vouchers/", views.spa_vouchers, name="spa_vouchers"),
    path("spa/vouchers/<int:pk>/redeem/", views.spa_voucher_redeem, name="spa_voucher_redeem"),
    # Waitlist
    path("spa/waitlist/", views.spa_waitlist, name="spa_waitlist"),
    # Client Profiles
    path("spa/clients/<int:guest_pk>/", views.spa_client_profile, name="spa_client_profile"),
]
